import { Documento } from './types'

const now = new Date().toISOString()

export const DOCUMENTOS_INICIAIS: Documento[] = [

  // ══════════════ SOPs ══════════════════════════════════════════════════════

  {
    id: 'sop-01',
    titulo: 'Onboarding de Novo Cliente',
    categoria: 'sop',
    descricao: 'Processo completo desde a assinatura do contrato até o início da operação. Garante que nenhum passo seja esquecido no primeiro mês.',
    tags: ['onboarding', 'cliente', 'kickoff'],
    responsavel_id: 'u3',
    status: 'ativo',
    versao: '1.2',
    criado_em: now,
    atualizado_em: now,
    conteudo: [
      { id: 's1', tipo: 'intro', texto: 'Este SOP garante que todo novo cliente receba a mesma experiência de entrada — organizada, profissional e sem ruídos. Execute todos os passos em até 72h após a assinatura do contrato.' },
      { id: 's2', tipo: 'secao', titulo: 'Fase 1 — Financeiro e Documentação', texto: 'Antes de qualquer ação operacional.' },
      { id: 's3', tipo: 'passo', titulo: 'Confirmar pagamento da 1ª parcela', itens: ['Verificar comprovante ou transação no banco', 'Registrar lancamento no módulo Financeiro', 'Emitir nota fiscal se necessário'] },
      { id: 's4', tipo: 'passo', titulo: 'Arquivar contrato assinado', itens: ['Salvar PDF no Google Drive na pasta do cliente', 'Registrar data de início e término no módulo Clientes', 'Adicionar parcelas programadas no Financeiro'] },
      { id: 's5', tipo: 'secao', titulo: 'Fase 2 — Setup Operacional', texto: 'Preparação da estrutura de trabalho.' },
      { id: 's6', tipo: 'passo', titulo: 'Criar cliente e projeto no sistema', itens: ['Cadastrar no módulo Clientes com todos os dados', 'Criar projeto em Projetos com data de início e entrega', 'Atribuir responsável e equipe', 'Definir tarefas do mês 1 com prazos'] },
      { id: 's7', tipo: 'passo', titulo: 'Solicitar acessos ao cliente', itens: ['Instagram (perfil comercial + senha)', 'Facebook Business Manager', 'Google Ads (convidar e-mail da agência)', 'Google Analytics e Google Search Console', 'WhatsApp Business (se Social Media)'] },
      { id: 's8', tipo: 'passo', titulo: 'Criar pasta do cliente no Google Drive', itens: ['Estrutura: /Clientes/[Nome]/Contratos, /Criativos, /Relatórios, /Briefings', 'Compartilhar pasta com o responsável do cliente'] },
      { id: 's9', tipo: 'secao', titulo: 'Fase 3 — Kickoff com o Cliente', texto: 'Alinhar expectativas antes de começar a produzir.' },
      { id: 's10', tipo: 'passo', titulo: 'Agendar reunião de kickoff', itens: ['Prazo: até 5 dias úteis após assinatura', 'Duração: 60 min', 'Pauta: apresentação da equipe, cronograma, processos de aprovação, canais de comunicação'] },
      { id: 's11', tipo: 'passo', titulo: 'Enviar e acompanhar briefing', itens: ['Usar template de briefing correspondente ao serviço contratado', 'Prazo para o cliente responder: 3 dias úteis', 'Sem briefing aprovado = sem produção iniciada'] },
      { id: 's12', tipo: 'destaque', titulo: 'Regra de ouro', texto: 'Nunca comece a produzir sem briefing preenchido e acessos recebidos. Dois dias de espera agora evitam duas semanas de retrabalho depois.', corDestaque: 'blue' },
      { id: 's13', tipo: 'passo', titulo: 'Enviar kit de boas-vindas', itens: ['Mensagem de WhatsApp apresentando a equipe', 'Cronograma visual do primeiro mês', 'Canais de contato e horários de atendimento', 'Prazo de resposta esperado do cliente (24h úteis)'] },
    ],
  },

  {
    id: 'sop-02',
    titulo: 'Entrega de Relatório Mensal',
    categoria: 'sop',
    descricao: 'Processo de coleta, montagem, revisão e entrega do relatório mensal de performance para cada cliente.',
    tags: ['relatório', 'mensal', 'performance'],
    responsavel_id: 'u1',
    status: 'ativo',
    versao: '1.0',
    criado_em: now,
    atualizado_em: now,
    conteudo: [
      { id: 's1', tipo: 'intro', texto: 'O relatório mensal é o principal instrumento de retenção de clientes. Um relatório bem feito que mostra resultado — mesmo quando o resultado não foi ideal — gera mais confiança do que silêncio.' },
      { id: 's2', tipo: 'aviso', titulo: 'Prazo fixo', texto: 'Todo relatório deve ser entregue até o 5º dia útil do mês seguinte. Atrasos no relatório indicam desorganização e aumentam o risco de churn.' },
      { id: 's3', tipo: 'passo', titulo: 'Coletar dados das plataformas (até dia 3)', itens: ['Meta Ads: exportar período completo do mês', 'Google Ads: exportar mesmo período', 'Instagram Insights: prints ou export de alcance, engajamento', 'Google Analytics: sessões, conversões, origem do tráfego'] },
      { id: 's4', tipo: 'passo', titulo: 'Montar relatório no template padrão', itens: ['Usar template "Relatório de Performance Mensal"', 'Preencher KPIs principais na capa', 'Adicionar análise em texto simples (não só números)', 'Comparar com mês anterior e com meta acordada'] },
      { id: 's5', tipo: 'passo', titulo: 'Revisão interna antes de enviar', itens: ['Outro membro da equipe revisa antes do cliente ver', 'Verificar: números batem com as plataformas?', 'Verificar: análise explica o porquê dos resultados?', 'Verificar: próximos passos estão claros?'] },
      { id: 's6', tipo: 'destaque', titulo: 'Como escrever análise que o cliente entende', texto: 'Evite: "CPM de R$12,40 com CTR de 2,3%". Prefira: "Cada 1.000 pessoas que viram o anúncio custou R$12. De cada 100 que viram, 2 clicaram — isso é acima da média do segmento."', corDestaque: 'emerald' },
      { id: 's7', tipo: 'passo', titulo: 'Enviar ao cliente', itens: ['Canal: WhatsApp (PDF) + e-mail', 'Incluir texto de contexto na mensagem (não só o arquivo)', 'Oferecer reunião de 30min para discussão se necessário'] },
      { id: 's8', tipo: 'passo', titulo: 'Registrar entrega no sistema', itens: ['Módulo Clientes → Entregas → Registrar "Relatório Mensal"', 'Mês de competência correto', 'Status: Entregue (aguardando aprovação do cliente)'] },
    ],
  },

  {
    id: 'sop-03',
    titulo: 'Fluxo de Criação e Aprovação de Peças',
    categoria: 'sop',
    descricao: 'Fluxo padrão para criação de criativos, copies e vídeos — do briefing à publicação. Define claramente quem faz o quê em cada etapa.',
    tags: ['criativo', 'aprovação', 'design', 'copy'],
    responsavel_id: 'u2',
    status: 'ativo',
    versao: '2.1',
    criado_em: now,
    atualizado_em: now,
    conteudo: [
      { id: 's1', tipo: 'intro', texto: 'Este fluxo se aplica a toda peça que será entregue ao cliente: post, story, arte para anúncio, vídeo, copy ou apresentação. Sem exceção.' },
      { id: 's2', tipo: 'lista', titulo: 'Regras que nunca podem ser quebradas', itens: ['Nenhuma peça vai ao cliente sem revisão interna', 'O número máximo de revisões por peça está no contrato — não ofereça mais sem cobrar', 'Feedback do cliente deve ser registrado no sistema (não só no WhatsApp)', 'Peça "aprovada no zap" não conta — precisa de aprovação formal no sistema'] },
      { id: 's3', tipo: 'passo', titulo: '1. Briefing', itens: ['Gestor alinha com cliente o que precisa ser criado', 'Preencher template de briefing correspondente', 'Definir prazo de entrega e número de revisões incluídas'] },
      { id: 's4', tipo: 'passo', titulo: '2. Produção', itens: ['Responsável recebe briefing e começa a produzir', 'Registrar tarefa no módulo Projetos com estimativa de horas', 'Prazo interno é sempre 2 dias antes do prazo combinado com o cliente'] },
      { id: 's5', tipo: 'passo', titulo: '3. Revisão Interna', itens: ['Peça pronta é revisada por outro membro da equipe', 'Verificar: está alinhado com o briefing?', 'Verificar: identidade visual do cliente foi respeitada?', 'Verificar: texto sem erros ortográficos?', 'Mover tarefa para "Revisão interna" no sistema'] },
      { id: 's6', tipo: 'passo', titulo: '4. Envio ao Cliente', itens: ['Mover tarefa para "Aguardando cliente" no sistema', 'Enviar com contexto: explicar o racional da peça', 'Informar o prazo para retorno (máximo 48h úteis)', 'Registrar revisões usadas na entrega'] },
      { id: 's7', tipo: 'passo', titulo: '5. Aprovação ou Revisão', itens: ['Cliente aprova → mover para "Aprovado" → Publicar ou entregar', 'Cliente pede alteração → registrar feedback → produzir novamente → revisão interna → reenviar', 'Limite de revisões atingido → abrir conversa sobre escopo extra antes de continuar'] },
      { id: 's8', tipo: 'destaque', titulo: 'Limite de revisões', texto: 'Ao atingir o limite contratual, pare e comunique: "Já utilizamos as X revisões incluídas no contrato. Podemos continuar com uma revisão adicional no valor de R$XXX." Isso protege a margem e educa o cliente.', corDestaque: 'amber' },
    ],
  },

  // ══════════════ CHECKLISTS ════════════════════════════════════════════════

  {
    id: 'cl-01',
    titulo: 'Checklist de Início de Projeto',
    categoria: 'checklist',
    descricao: 'Execute este checklist antes de declarar que um projeto começou. Cada item não marcado é um risco em potencial.',
    tags: ['projeto', 'início', 'setup'],
    responsavel_id: 'u1',
    status: 'ativo',
    versao: '1.0',
    criado_em: now,
    atualizado_em: now,
    conteudo: [
      { id: 's1', tipo: 'intro', texto: 'Use este checklist para cada novo projeto ou início de mês em contratos retainer. Execute na ordem indicada.' },
      { id: 's2', tipo: 'checklist', titulo: 'Financeiro', itens: ['Contrato assinado recebido e arquivado', 'Primeiro pagamento confirmado no banco', 'Nota fiscal emitida', 'Parcelas futuras programadas no sistema Financeiro'] },
      { id: 's3', tipo: 'checklist', titulo: 'Cadastro no Sistema', itens: ['Cliente cadastrado no módulo Clientes', 'Contrato com serviços e valor registrado', 'Projeto criado em Projetos com data de entrega', 'Tarefas do mês criadas e atribuídas', 'Responsável e equipe definidos'] },
      { id: 's4', tipo: 'checklist', titulo: 'Acessos e Ferramentas', itens: ['Instagram / Facebook — acesso recebido', 'Google Ads — conta vinculada à agência', 'Google Analytics — acesso de visualização', 'Google Drive — pasta do cliente criada e organizada', 'WhatsApp — número do cliente salvo nos contatos da equipe'] },
      { id: 's5', tipo: 'checklist', titulo: 'Alinhamento com o Cliente', itens: ['Kickoff realizado ou agendado', 'Briefing enviado ao cliente', 'Briefing respondido e aprovado', 'Cronograma do mês 1 enviado ao cliente', 'Canais e horários de comunicação combinados'] },
    ],
  },

  {
    id: 'cl-02',
    titulo: 'Checklist de Entrega ao Cliente',
    categoria: 'checklist',
    descricao: 'Antes de enviar qualquer material ao cliente. Zero material sai sem este checklist.',
    tags: ['entrega', 'qualidade', 'revisão'],
    responsavel_id: 'u1',
    status: 'ativo',
    versao: '1.1',
    criado_em: now,
    atualizado_em: now,
    conteudo: [
      { id: 's1', tipo: 'aviso', titulo: 'Regra absoluta', texto: 'Nenhum material vai ao cliente sem revisão interna de outra pessoa da equipe. Se você produziu, você não revisa — outra pessoa revisa.' },
      { id: 's2', tipo: 'checklist', titulo: 'Conteúdo', itens: ['O material está alinhado com o briefing?', 'Tom de voz do cliente foi respeitado?', 'Informações do produto/serviço estão corretas?', 'CTAs (chamadas para ação) estão presentes e claros?'] },
      { id: 's3', tipo: 'checklist', titulo: 'Visual', itens: ['Identidade visual do cliente foi seguida (cores, fontes, logo)?', 'Logo está na versão correta e com tamanho adequado?', 'Resolução adequada para o formato de entrega?', 'Versão mobile revisada (se aplicável)?'] },
      { id: 's4', tipo: 'checklist', titulo: 'Texto', itens: ['Ortografia e gramática revisadas?', 'Emojis e hashtags conferidos?', 'Links testados (se houver)?', 'Datas e informações temporais estão corretas?'] },
      { id: 's5', tipo: 'checklist', titulo: 'Processo', itens: ['Revisão interna realizada por outra pessoa?', 'Tarefa movida para "Aguardando cliente" no sistema?', 'Número de revisões usado foi registrado?', 'Mensagem de contexto preparada para acompanhar o material?'] },
    ],
  },

  {
    id: 'cl-03',
    titulo: 'Checklist de Reunião com Cliente',
    categoria: 'checklist',
    descricao: 'Antes, durante e depois de qualquer reunião. Garante que nenhuma reunião termine sem próximos passos definidos.',
    tags: ['reunião', 'cliente', 'comunicação'],
    responsavel_id: 'u3',
    status: 'ativo',
    versao: '1.0',
    criado_em: now,
    atualizado_em: now,
    conteudo: [
      { id: 's1', tipo: 'checklist', titulo: 'Antes da Reunião', itens: ['Pauta definida e enviada ao cliente com antecedência', 'Material de suporte preparado (relatório, criativos, proposta)', 'Link da reunião enviado 1 dia antes', 'Lembrete enviado 1h antes via WhatsApp'] },
      { id: 's2', tipo: 'checklist', titulo: 'Durante a Reunião', itens: ['Apresentar pauta no início', 'Registrar decisões importantes em tempo real', 'Definir próximos passos com responsáveis e prazos', 'Confirmar satisfação do cliente antes de encerrar'] },
      { id: 's3', tipo: 'checklist', titulo: 'Após a Reunião (até 2h)', itens: ['Ata com resumo enviada via WhatsApp', 'Próximos passos registrados no sistema (tarefas criadas)', 'Follow-up agendado se necessário', 'Atualizações de projeto ou contrato realizadas no sistema'] },
      { id: 's4', tipo: 'destaque', titulo: 'Por que a ata é obrigatória?', texto: 'Memórias divergem. "Você disse que ia entregar na sexta" vs "Eu disse até segunda". A ata evita conflitos e cria responsabilidade mútua.', corDestaque: 'blue' },
    ],
  },

  {
    id: 'cl-04',
    titulo: 'Checklist de Relatório Mensal',
    categoria: 'checklist',
    descricao: 'Garante que o relatório seja completo, correto e entregue no prazo. Um item por item, sem pular.',
    tags: ['relatório', 'mensal', 'qualidade'],
    responsavel_id: 'u1',
    status: 'ativo',
    versao: '1.0',
    criado_em: now,
    atualizado_em: now,
    conteudo: [
      { id: 's1', tipo: 'checklist', titulo: 'Coleta de Dados', itens: ['Meta Ads exportado (período correto)', 'Google Ads exportado (período correto)', 'Instagram Insights coletado', 'GA4 / Analytics coletado', 'Dados de vendas/leads do cliente recebidos (se necessário)'] },
      { id: 's2', tipo: 'checklist', titulo: 'Montagem', itens: ['Template correto utilizado', 'KPIs da capa preenchidos', 'Comparativo com mês anterior incluído', 'Comparativo com meta acordada incluído', 'Análise em texto simples (não só números)', 'Próximos passos da agência para o próximo mês incluídos'] },
      { id: 's3', tipo: 'checklist', titulo: 'Revisão Interna', itens: ['Números conferidos com as plataformas', 'Ortografia revisada', 'Outro membro da equipe revisou', 'Prazo de entrega está dentro do combinado?'] },
      { id: 's4', tipo: 'checklist', titulo: 'Entrega', itens: ['Enviado por WhatsApp (PDF) E por e-mail', 'Mensagem de contexto incluída (não só o arquivo)', 'Oferta de reunião de resultados feita', 'Entrega registrada no módulo Clientes do sistema'] },
    ],
  },

  // ══════════════ TEMPLATES ═════════════════════════════════════════════════

  {
    id: 'tp-01',
    titulo: 'Briefing de Social Media',
    categoria: 'template',
    descricao: 'Template completo para coletar todas as informações necessárias antes de iniciar a gestão de redes sociais de um cliente.',
    tags: ['briefing', 'social media', 'instagram'],
    responsavel_id: 'u1',
    status: 'ativo',
    versao: '1.3',
    criado_em: now,
    atualizado_em: now,
    conteudo: [
      { id: 's1', tipo: 'intro', texto: 'Preencha com o cliente em reunião ou envie para preenchimento assíncrono. Sem este briefing aprovado, nenhum conteúdo é produzido.' },
      { id: 's2', tipo: 'lista', titulo: '1. Sobre o Negócio', itens: ['Nome da empresa e segmento', 'Produto ou serviço principal (descreva em 2 linhas)', 'Diferencial competitivo: o que você tem que os concorrentes não têm?', 'Ticket médio e faixa de preço', 'Maior dor que você resolve para o cliente'] },
      { id: 's3', tipo: 'lista', titulo: '2. Público-Alvo', itens: ['Idade, gênero, cidade', 'Profissão e renda aproximada', 'Interesses e hobbies', 'Onde consome conteúdo (Instagram, TikTok, YouTube?)', 'O que ele procura antes de comprar?'] },
      { id: 's4', tipo: 'lista', titulo: '3. Tom de Voz', itens: ['Como você se comunica: formal ou informal?', '3 adjetivos que definem a sua marca', '3 adjetivos que sua marca NUNCA deve ser', 'Referências de marcas que você admira (por que?)', 'O que você NÃO quer que apareça no seu perfil?'] },
      { id: 's5', tipo: 'lista', titulo: '4. Conteúdo', itens: ['Quais serviços / produtos serão divulgados?', 'Tem fotos e vídeos disponíveis? (se sim, compartilhar pasta)', 'Calendário de eventos, promoções ou lançamentos previstos', 'Temas que você NUNCA quer abordar', 'Hashtags que já usa ou quer usar'] },
      { id: 's6', tipo: 'lista', titulo: '5. Objetivos', itens: ['O que você espera do primeiro mês?', 'Métricas que importam para você (seguidores, alcance, mensagens, vendas?)', 'Meta numérica (se tiver): ex. chegar a X seguidores', 'O que seria um ótimo resultado em 3 meses?'] },
      { id: 's7', tipo: 'lista', titulo: '6. Operacional', itens: ['Quem vai aprovar os conteúdos?', 'Qual o prazo de retorno para aprovações (em dias úteis)?', 'Canal de comunicação preferido com a agência (WhatsApp / e-mail?)', 'Senha e acesso às redes fornecidos?'] },
    ],
  },

  {
    id: 'tp-02',
    titulo: 'Briefing de Tráfego Pago',
    categoria: 'template',
    descricao: 'Formulário para coletar todas as informações antes de criar campanhas no Meta Ads e Google Ads.',
    tags: ['briefing', 'tráfego pago', 'meta ads', 'google ads'],
    responsavel_id: 'u1',
    status: 'ativo',
    versao: '1.1',
    criado_em: now,
    atualizado_em: now,
    conteudo: [
      { id: 's1', tipo: 'intro', texto: 'Preencher ANTES de subir qualquer campanha. Campanhas sem briefing têm 3x mais chance de não atingir o objetivo.' },
      { id: 's2', tipo: 'lista', titulo: '1. Objetivo da Campanha', itens: ['O que você quer que aconteça quando alguém clicar no anúncio?', 'Resultado esperado: gerar leads, vender diretamente, direcionar ao WhatsApp, aumentar seguidores?', 'Como você saberá se a campanha teve sucesso? (métrica e número)', 'Prazo da campanha: data de início e fim'] },
      { id: 's3', tipo: 'lista', titulo: '2. Público', itens: ['Idade, gênero, localização', 'Interesses e comportamentos', 'Você tem lista de clientes para criar Lookalike? (sim/não)', 'Tem pixel do Meta instalado no site? E tag do Google?', 'Público que NÃO deve ver o anúncio'] },
      { id: 's4', tipo: 'lista', titulo: '3. Orçamento', itens: ['Verba total disponível para o período', 'Preferência: orçamento diário ou vitalício?', 'Há alguma data especial que precisa de mais verba?', 'Qual o custo máximo aceitável por lead / por venda (CPA)?'] },
      { id: 's5', tipo: 'lista', titulo: '4. Criativos', itens: ['Tem imagens ou vídeos prontos? (compartilhar)', 'Precisa que a agência crie os criativos?', 'Mensagem principal que o anúncio deve transmitir', 'Oferta ou diferencial que deve aparecer (desconto, prazo, bônus?)', 'CTA desejado: "Saiba mais", "Fale conosco", "Compre agora"?'] },
      { id: 's6', tipo: 'lista', titulo: '5. Destino do Clique', itens: ['URL da landing page ou site', 'WhatsApp Business (número correto)', 'A página está otimizada para mobile?', 'Tem formulário de captura? Está funcionando?'] },
      { id: 's7', tipo: 'destaque', titulo: 'Antes de subir a campanha', texto: 'Confirme: pixel instalado e disparando? Formulário funcionando? UTMs configuradas para rastreamento?', corDestaque: 'amber' },
    ],
  },

  {
    id: 'tp-03',
    titulo: 'Template de Relatório Mensal',
    categoria: 'template',
    descricao: 'Estrutura padrão do relatório mensal de performance. Use este template para garantir consistência em todos os clientes.',
    tags: ['relatório', 'template', 'performance'],
    responsavel_id: 'u1',
    status: 'ativo',
    versao: '2.0',
    criado_em: now,
    atualizado_em: now,
    conteudo: [
      { id: 's1', tipo: 'intro', texto: 'Este é o esqueleto do relatório. Adapte os KPIs de acordo com os serviços contratados. O idioma deve ser sempre simples — o cliente não é especialista em marketing.' },
      { id: 's2', tipo: 'lista', titulo: 'Página 1 — Capa e Resumo Executivo', itens: ['Logo do cliente + logo da agência', 'Mês de referência', '3–4 KPIs principais em destaque visual (o que foi alcançado vs meta)', 'Frase de 2 linhas resumindo o mês: "Em março, X aconteceu e o resultado foi Y."'] },
      { id: 's3', tipo: 'lista', titulo: 'Página 2 — Resultados Detalhados', itens: ['Alcance total (quantas pessoas viram seu conteúdo)', 'Engajamento (curtidas, comentários, compartilhamentos, salvamentos)', 'Crescimento de seguidores: início vs fim do mês', 'Comparativo com mês anterior: seta verde/vermelha'] },
      { id: 's4', tipo: 'lista', titulo: 'Página 3 — Tráfego Pago (se aplicável)', itens: ['Investimento total no período', 'Impressões e alcance pago', 'CPM (custo por mil impressões)', 'CPC (custo por clique)', 'CTR (taxa de clique)', 'Conversões / leads / mensagens recebidas', 'CPA (custo por aquisição ou lead)'] },
      { id: 's5', tipo: 'lista', titulo: 'Página 4 — Análise e Contexto', itens: ['Por que os resultados foram assim? (análise em texto simples)', 'O que funcionou bem? (2–3 pontos)', 'O que precisa melhorar? (1–2 pontos)', 'Como comparamos com a média do segmento?'] },
      { id: 's6', tipo: 'lista', titulo: 'Página 5 — Próximos Passos', itens: ['O que a agência vai fazer diferente no próximo mês', '1–2 sugestões para o cliente (ação que depende dele)', 'Datas importantes do próximo mês', 'Proposta de reunião de resultados (opcional)'] },
      { id: 's7', tipo: 'destaque', titulo: 'Regra dos números', texto: 'Nunca apresente número sem contexto. "2.340 alcance" não significa nada. "2.340 pessoas únicas viram seu perfil — 18% a mais que fevereiro" significa muito.', corDestaque: 'emerald' },
    ],
  },

  // ══════════════ CONTRATOS ═════════════════════════════════════════════════

  {
    id: 'ct-01',
    titulo: 'Cláusulas Essenciais — Contrato Retainer',
    categoria: 'contrato',
    descricao: 'As cláusulas que todo contrato de retainer precisa ter para proteger a agência e alinhar expectativas com o cliente.',
    tags: ['contrato', 'retainer', 'jurídico'],
    responsavel_id: 'u3',
    status: 'ativo',
    versao: '1.0',
    criado_em: now,
    atualizado_em: now,
    conteudo: [
      { id: 's1', tipo: 'aviso', titulo: 'Atenção', texto: 'Este documento é um guia de referência, não um contrato pronto para uso. Sempre valide o contrato final com um advogado.' },
      { id: 's2', tipo: 'lista', titulo: '1. Objeto do Contrato', itens: ['Descrever exatamente os serviços contratados (sem ambiguidade)', 'Listar o que NÃO está incluído no escopo', 'Número de entregas por mês (ex: 12 posts, 2 relatórios)', 'Número de revisões incluídas por entregável'] },
      { id: 's3', tipo: 'lista', titulo: '2. Pagamento', itens: ['Valor mensal e data de vencimento', 'Multa por atraso (geralmente 2% ao mês + correção)', 'Política de suspensão: serviços pausam após X dias de inadimplência', 'Reajuste anual: indexado ao IPCA ou fixo em X%', 'Forma de pagamento aceita (PIX / boleto / transferência)'] },
      { id: 's4', tipo: 'lista', titulo: '3. Prazos e Entregas', itens: ['Prazo para o cliente fornecer materiais / briefing (ex: até dia 5)', 'Prazo para aprovação de peças pelo cliente (ex: 48h úteis)', 'Consequência de atraso do cliente: entrega postergada proporcionalmente', 'Canal oficial de aprovação (e-mail ou sistema — WhatsApp NÃO vale como aprovação oficial)'] },
      { id: 's5', tipo: 'lista', titulo: '4. Propriedade Intelectual', itens: ['Arquivos produzidos são de propriedade do cliente após quitação', 'Arquivos de trabalho (PSDs, AIs) ficam com a agência', 'A agência pode usar o trabalho em portfólio (salvo cláusula de confidencialidade)'] },
      { id: 's6', tipo: 'lista', titulo: '5. Rescisão', itens: ['Aviso prévio: 30 dias de antecedência por qualquer das partes', 'Rescisão imediata por inadimplência superior a X dias', 'Devolução de materiais e acessos em até 5 dias após rescisão', 'Trabalhos em andamento: o que acontece com eles?'] },
      { id: 's7', tipo: 'destaque', titulo: 'A cláusula mais importante', texto: 'Defina explicitamente o canal oficial de aprovação. "Aprovado pelo WhatsApp" gera conflitos. O contrato deve dizer que só vale aprovação por e-mail ou pelo sistema de gestão.', corDestaque: 'amber' },
    ],
  },

  // ══════════════ BRIEFINGS ═════════════════════════════════════════════════

  {
    id: 'br-01',
    titulo: 'Briefing de Identidade Visual',
    categoria: 'briefing',
    descricao: 'Formulário para projetos de criação ou redesign de identidade visual. Coletar antes de criar qualquer logotipo ou material de marca.',
    tags: ['branding', 'identidade visual', 'logo'],
    responsavel_id: 'u2',
    status: 'ativo',
    versao: '1.0',
    criado_em: now,
    atualizado_em: now,
    conteudo: [
      { id: 's1', tipo: 'intro', texto: 'Preencher com o cliente antes de iniciar qualquer projeto de identidade visual. Mínimo de 45 minutos de conversa. Não aceite respostas vagas — aprofunde cada pergunta.' },
      { id: 's2', tipo: 'lista', titulo: '1. Sobre o Negócio', itens: ['Qual o negócio e o que ele entrega ao cliente?', 'Há quanto tempo existe? Tem histórico para contar?', 'Qual o maior diferencial em relação aos concorrentes?', 'Onde atua: local, regional, nacional, online?'] },
      { id: 's3', tipo: 'lista', titulo: '2. Posicionamento de Marca', itens: ['Se sua marca fosse uma pessoa famosa, quem seria? Por quê?', 'Se fosse um carro, qual seria?', '3 palavras que devem vir à mente quando alguém vê sua marca', '3 palavras que sua marca NUNCA deve transmitir', 'Você é mais: moderno ou clássico? Jovem ou maduro? Colorido ou sóbrio?'] },
      { id: 's4', tipo: 'lista', titulo: '3. Público-Alvo', itens: ['Descreva seu cliente ideal em detalhes', 'Faixa etária e gênero predominante', 'Estilo de vida e valores', 'Onde ele consome referências visuais?'] },
      { id: 's5', tipo: 'lista', titulo: '4. Referências Visuais', itens: ['Marcas que você admira visualmente (e por quê)', 'Marcas do seu segmento que você acha que se posicionam bem', 'Cores que você gosta (e cores que você definitivamente não quer)', 'Estilos: minimalista, expressivo, orgânico, tecnológico?', 'Compartilhe exemplos: Pinterest, Instagram, etc.'] },
      { id: 's6', tipo: 'lista', titulo: '5. Aplicações', itens: ['Onde a identidade visual será usada: redes sociais, site, fachada, uniforme, embalagem?', 'Precisa funcionar bem em pequeno (perfil de rede) e em grande (banner, fachada)?', 'Tem impressão em preto e branco prevista?', 'Materiais digitais predominam ou materiais físicos?'] },
    ],
  },

  {
    id: 'br-02',
    titulo: 'Briefing de Lançamento',
    categoria: 'briefing',
    descricao: 'Formulário estruturado para campanhas de lançamento de produto, serviço ou evento. Captura todos os dados necessários para planejamento estratégico.',
    tags: ['lançamento', 'campanha', 'produto'],
    responsavel_id: 'u3',
    status: 'ativo',
    versao: '1.0',
    criado_em: now,
    atualizado_em: now,
    conteudo: [
      { id: 's1', tipo: 'intro', texto: 'Use este briefing para qualquer lançamento: produto, serviço, evento, curso. Preencher com no mínimo 3 semanas de antecedência ao lançamento.' },
      { id: 's2', tipo: 'lista', titulo: '1. O que vai ser lançado', itens: ['Nome do produto / serviço / evento', 'Descrição em 3 linhas (como você explicaria para um amigo)', 'Preço e condições de pagamento', 'Disponibilidade: online, presencial, por tempo limitado?', 'Quantas unidades / vagas disponíveis?'] },
      { id: 's3', tipo: 'lista', titulo: '2. Datas e Cronograma', itens: ['Data de abertura do carrinho / inscrições', 'Data de encerramento', 'Datas de marcos importantes (webinar, evento, live)', 'Data de entrega do produto (se aplicável)'] },
      { id: 's4', tipo: 'lista', titulo: '3. Público e Oferta', itens: ['Para quem é exatamente este lançamento?', 'Qual o maior problema que ele resolve?', 'Por que a pessoa deve comprar AGORA e não depois? (urgência)', 'Qual o bônus ou diferencial desta oferta vs sempre disponível?'] },
      { id: 's5', tipo: 'lista', titulo: '4. Estratégia de Marketing', itens: ['Tráfego pago previsto? Qual verba?', 'Base de e-mail ou lista de WhatsApp disponível?', 'Parceiros ou afiliados envolvidos?', 'Influencers serão usados?', 'Onde a venda acontece: Hotmart, site próprio, WhatsApp?'] },
      { id: 's6', tipo: 'lista', titulo: '5. Materiais Necessários', itens: ['Página de vendas (quem cria?)', 'Vídeos de captação (duração, roteiro)', 'Criativos para anúncios (formatos: feed, story, reels)', 'E-mails da sequência de lançamento (quantos?)', 'Posts orgânicos de aquecimento'] },
      { id: 's7', tipo: 'destaque', titulo: 'Defina o sucesso antes de começar', texto: 'Quantas vendas são consideradas sucesso? Qual o faturamento mínimo esperado? Com essas metas claras, é possível calcular quanto investir e tomar decisões no meio do lançamento.', corDestaque: 'emerald' },
    ],
  },
]
