import { Lead, Interacao, FollowUp } from './types'

export const mockLeads: Lead[] = [
  {
    id: 'l1',
    nome_empresa: 'TechSoluções Ltda',
    nome_contato: 'João Silva',
    cargo_contato: 'ceo_socio',
    email: 'joao@techsolucoes.com.br',
    telefone: '(11) 98765-4321',
    whatsapp: '11987654321',
    cnpj: '12.345.678/0001-99',
    site: 'techsolucoes.com.br',
    segmento: 'saas',
    porte: 'media',
    cidade: 'São Paulo',
    estado: 'SP',
    fonte: 'linkedin',
    responsavel_id: 'u1',
    status: 'proposta_enviada',
    valor_estimado: 9600,
    data_fechamento_estimada: '2026-05-15',
    probabilidade: 70,
    observacoes: 'Querem lançar campanha de inbound para captação de leads B2B.',
    score_perfil: 30,
    score_engajamento: 35,
    score_timing: 18,
    score_total: 83,
    criado_em: '2026-04-01T09:00:00Z',
    atualizado_em: '2026-04-22T14:30:00Z',
  },
  {
    id: 'l2',
    nome_empresa: 'Grupo Farma Brasil',
    nome_contato: 'Fernanda Rocha',
    cargo_contato: 'diretor',
    email: 'fernanda@grupofarmabrasil.com.br',
    telefone: '(21) 3456-7890',
    whatsapp: '21934567890',
    site: 'grupofarmabrasil.com.br',
    segmento: 'saude',
    porte: 'grande',
    cidade: 'Rio de Janeiro',
    estado: 'RJ',
    fonte: 'indicacao',
    fonte_detalhe: 'Indicado por Marcus (cliente ativo)',
    responsavel_id: 'u2',
    status: 'negociando',
    valor_estimado: 18000,
    data_fechamento_estimada: '2026-05-30',
    probabilidade: 55,
    score_perfil: 37,
    score_engajamento: 28,
    score_timing: 15,
    score_total: 80,
    criado_em: '2026-04-10T11:00:00Z',
    atualizado_em: '2026-04-23T10:00:00Z',
  },
  {
    id: 'l3',
    nome_empresa: 'Moda Fit Store',
    nome_contato: 'Carlos Mendes',
    cargo_contato: 'ceo_socio',
    email: 'carlos@modafit.com.br',
    telefone: '(31) 99876-5432',
    whatsapp: '31998765432',
    site: 'modafit.com.br',
    segmento: 'ecommerce',
    porte: 'pequena',
    cidade: 'Belo Horizonte',
    estado: 'MG',
    fonte: 'instagram',
    responsavel_id: 'u1',
    status: 'em_conversa',
    valor_estimado: 5400,
    probabilidade: 35,
    observacoes: 'Quer escalar tráfego pago no Instagram. Tem lançamento de coleção em junho.',
    score_perfil: 26,
    score_engajamento: 25,
    score_timing: 20,
    score_total: 71,
    criado_em: '2026-04-15T14:00:00Z',
    atualizado_em: '2026-04-24T09:00:00Z',
  },
  {
    id: 'l4',
    nome_empresa: 'EduTech Academy',
    nome_contato: 'Priscila Torres',
    cargo_contato: 'gerente',
    email: 'priscila@edutechacademy.com.br',
    telefone: '(51) 3210-9876',
    whatsapp: '51932109876',
    segmento: 'educacao',
    porte: 'media',
    cidade: 'Porto Alegre',
    estado: 'RS',
    fonte: 'google',
    responsavel_id: 'u3',
    status: 'abordado',
    valor_estimado: 7200,
    probabilidade: 20,
    score_perfil: 23,
    score_engajamento: 5,
    score_timing: 10,
    score_total: 38,
    criado_em: '2026-04-18T08:30:00Z',
    atualizado_em: '2026-04-18T08:30:00Z',
  },
  {
    id: 'l5',
    nome_empresa: 'Construtora Alvorada',
    nome_contato: 'Roberto Lima',
    cargo_contato: 'diretor',
    email: 'roberto@alvorada.com.br',
    telefone: '(41) 3344-5566',
    whatsapp: '41933445566',
    cnpj: '98.765.432/0001-11',
    site: 'alvorada.com.br',
    segmento: 'imoveis',
    porte: 'grande',
    cidade: 'Curitiba',
    estado: 'PR',
    fonte: 'evento',
    fonte_detalhe: 'Conecta Mkt 2026',
    responsavel_id: 'u2',
    status: 'qualificado',
    valor_estimado: 14400,
    probabilidade: 15,
    observacoes: 'Precisa de branding completo + geração de leads para lançamento imobiliário.',
    score_perfil: 37,
    score_engajamento: 10,
    score_timing: 8,
    score_total: 55,
    criado_em: '2026-04-20T16:00:00Z',
    atualizado_em: '2026-04-20T16:00:00Z',
  },
  {
    id: 'l6',
    nome_empresa: 'Ótica Vision',
    nome_contato: 'Mariana Duarte',
    cargo_contato: 'ceo_socio',
    email: 'mariana@oticavision.com.br',
    telefone: '(85) 99123-4567',
    whatsapp: '85991234567',
    segmento: 'varejo',
    porte: 'pequena',
    cidade: 'Fortaleza',
    estado: 'CE',
    fonte: 'whatsapp',
    responsavel_id: 'u1',
    status: 'identificado',
    probabilidade: 5,
    score_perfil: 23,
    score_engajamento: 0,
    score_timing: 5,
    score_total: 28,
    criado_em: '2026-04-25T07:45:00Z',
    atualizado_em: '2026-04-25T07:45:00Z',
  },
  {
    id: 'l7',
    nome_empresa: 'Studio K Arquitetura',
    nome_contato: 'Kleber Nunes',
    cargo_contato: 'ceo_socio',
    email: 'kleber@studiok.com.br',
    telefone: '(11) 97654-3210',
    whatsapp: '11976543210',
    site: 'studiok.com.br',
    segmento: 'servicos',
    porte: 'micro',
    cidade: 'São Paulo',
    estado: 'SP',
    fonte: 'site',
    responsavel_id: 'u3',
    status: 'fechado',
    valor_estimado: 4800,
    probabilidade: 100,
    score_perfil: 21,
    score_engajamento: 38,
    score_timing: 17,
    score_total: 76,
    criado_em: '2026-03-10T10:00:00Z',
    atualizado_em: '2026-04-05T15:00:00Z',
  },
  {
    id: 'l8',
    nome_empresa: 'Indústria Metalforte',
    nome_contato: 'Paulo Saraiva',
    cargo_contato: 'gerente',
    email: 'paulo@metalforte.com.br',
    telefone: '(11) 3456-7891',
    whatsapp: '11934567891',
    segmento: 'industria',
    porte: 'grande',
    cidade: 'Santo André',
    estado: 'SP',
    fonte: 'linkedin',
    responsavel_id: 'u2',
    status: 'sem_interesse',
    motivo_perda: 'Escolheu outra agência com menor preço',
    probabilidade: 0,
    score_perfil: 28,
    score_engajamento: 15,
    score_timing: 5,
    score_total: 48,
    criado_em: '2026-03-20T09:00:00Z',
    atualizado_em: '2026-04-18T17:00:00Z',
  },
]

export const mockInteracoes: Interacao[] = [
  {
    id: 'i1',
    lead_id: 'l1',
    usuario_nome: 'Lucas Andrade',
    tipo: 'ligacao_realizada',
    conteudo: 'Apresentação inicial. João demonstrou forte interesse em inbound B2B. Budget confirmado: R$8–12k/mês.',
    duracao_minutos: 28,
    sentimento: 'positivo',
    proximo_passo: 'Enviar proposta até sexta-feira',
    criado_em: '2026-04-20T10:00:00Z',
  },
  {
    id: 'i2',
    lead_id: 'l1',
    usuario_nome: 'Lucas Andrade',
    tipo: 'proposta_enviada',
    conteudo: 'Proposta de R$9.600/mês enviada por e-mail. Inclui gestão de tráfego, conteúdo e relatórios.',
    sentimento: 'neutro',
    proximo_passo: 'Aguardar retorno até 25/04. Follow-up se não responder.',
    criado_em: '2026-04-22T14:30:00Z',
  },
  {
    id: 'i3',
    lead_id: 'l1',
    usuario_nome: 'Lucas Andrade',
    tipo: 'whatsapp_enviado',
    conteudo: 'Oi João, tudo bem? Queria saber se teve chance de ver a proposta. Fico à disposição para tirar dúvidas!',
    sentimento: 'neutro',
    criado_em: '2026-04-10T09:00:00Z',
  },
  {
    id: 'i4',
    lead_id: 'l2',
    usuario_nome: 'Ana Costa',
    tipo: 'reuniao_realizada',
    conteudo: 'Reunião de descoberta. Grupo Farma quer reposicionar marca para público mais jovem. Decisão final com board em maio.',
    duracao_minutos: 52,
    sentimento: 'positivo',
    proximo_passo: 'Apresentar estudo de caso e estratégia de branding na próxima reunião.',
    criado_em: '2026-04-23T10:00:00Z',
  },
  {
    id: 'i5',
    lead_id: 'l3',
    usuario_nome: 'Lucas Andrade',
    tipo: 'whatsapp_recebido',
    conteudo: 'Carlos respondeu: "Sim, me interessa muito! Quando podemos conversar melhor? Temos lançamento em junho e precisamos acelerar."',
    sentimento: 'positivo',
    proximo_passo: 'Ligar amanhã para qualificação detalhada',
    criado_em: '2026-04-24T09:00:00Z',
  },
  {
    id: 'i6',
    lead_id: 'l7',
    usuario_nome: 'Rafael Mendes',
    tipo: 'mudanca_estagio',
    conteudo: 'Lead movido para "Fechado"',
    sentimento: 'neutro',
    criado_em: '2026-04-05T15:00:00Z',
  },
]

export const mockFollowUps: FollowUp[] = [
  {
    id: 'f1',
    lead_id: 'l1',
    tipo: 'ligar',
    data_hora: '2026-04-25T10:00:00Z',
    prioridade: 'urgente',
    descricao: 'Proposta enviada há 3 dias. Verificar se teve dúvidas e acelerar decisão.',
    status: 'pendente',
    criado_em: '2026-04-22T14:30:00Z',
  },
  {
    id: 'f2',
    lead_id: 'l2',
    tipo: 'email',
    data_hora: '2026-04-26T09:00:00Z',
    prioridade: 'alta',
    descricao: 'Enviar estudo de caso de reposicionamento de marca no setor farmacêutico.',
    status: 'pendente',
    criado_em: '2026-04-23T10:30:00Z',
  },
  {
    id: 'f3',
    lead_id: 'l3',
    tipo: 'ligar',
    data_hora: '2026-04-25T14:00:00Z',
    prioridade: 'alta',
    descricao: 'Qualificação detalhada. Perguntar sobre budget, decisor final e urgência do lançamento.',
    status: 'pendente',
    criado_em: '2026-04-24T09:15:00Z',
  },
  {
    id: 'f4',
    lead_id: 'l4',
    tipo: 'whatsapp',
    data_hora: '2026-04-25T11:00:00Z',
    prioridade: 'normal',
    descricao: 'Follow-up #1: verificar se recebeu a mensagem de apresentação.',
    status: 'pendente',
    criado_em: '2026-04-18T08:30:00Z',
  },
]
