import { Projeto, Tarefa, Comentario } from './types'

export const mockProjetos: Projeto[] = [
  {
    id: 'p1',
    cliente_id: 'c1',
    contrato_id: 'k1',
    nome: 'Social Media Studio K — Abril/2026',
    descricao: 'Produção e gestão completa de conteúdo para Instagram e LinkedIn do Studio K.',
    tipo: 'retainer_mensal',
    status: 'em_andamento',
    prioridade: 'normal',
    responsavel_id: 'u3',
    equipe_ids: ['u3'],
    data_inicio: '2026-04-01',
    data_entrega_prevista: '2026-04-30',
    progresso: 60,
    tags: ['social-media', 'design', 'copy'],
    criado_em: '2026-04-01T09:00:00Z',
    atualizado_em: '2026-04-24T10:00:00Z',
  },
  {
    id: 'p2',
    cliente_id: 'c2',
    contrato_id: 'k2',
    nome: 'Campanha Indústria 4.0 — Grupo Santos',
    descricao: 'Campanha de tráfego pago Google + Meta para captação de leads B2B no segmento industrial.',
    tipo: 'campanha',
    status: 'em_andamento',
    prioridade: 'alta',
    responsavel_id: 'u1',
    equipe_ids: ['u1', 'u3'],
    data_inicio: '2026-04-01',
    data_entrega_prevista: '2026-04-30',
    progresso: 78,
    tags: ['trafego-pago', 'b2b', 'google-ads'],
    criado_em: '2026-04-01T09:00:00Z',
    atualizado_em: '2026-04-24T09:00:00Z',
  },
  {
    id: 'p3',
    cliente_id: 'c2',
    contrato_id: 'k2',
    nome: 'Blog Q2/2026 — Grupo Santos',
    descricao: '8 artigos otimizados para SEO sobre indústria, automação e inovação.',
    tipo: 'retainer_mensal',
    status: 'planejamento',
    prioridade: 'normal',
    responsavel_id: 'u1',
    equipe_ids: ['u1'],
    data_inicio: '2026-04-15',
    data_entrega_prevista: '2026-06-30',
    progresso: 12,
    tags: ['seo', 'conteudo', 'blog'],
    criado_em: '2026-04-15T09:00:00Z',
    atualizado_em: '2026-04-20T09:00:00Z',
  },
  {
    id: 'p4',
    cliente_id: 'c3',
    contrato_id: 'k3',
    nome: 'Campanha Consultas — Clínica NovaSaúde',
    descricao: 'Campanha Meta Ads para geração de agendamentos de consulta.',
    tipo: 'campanha',
    status: 'aguardando_cliente',
    prioridade: 'urgente',
    responsavel_id: 'u2',
    equipe_ids: ['u2', 'u3'],
    data_inicio: '2026-04-05',
    data_entrega_prevista: '2026-04-25',
    progresso: 45,
    tags: ['meta-ads', 'saude', 'agendamento'],
    criado_em: '2026-04-05T09:00:00Z',
    atualizado_em: '2026-04-19T14:00:00Z',
  },
  {
    id: 'p5',
    cliente_id: 'c4',
    contrato_id: 'k4',
    nome: 'Redesign E-commerce — E-Bike Shop',
    descricao: 'Identidade visual + layout e-commerce + configuração da loja.',
    tipo: 'site',
    status: 'em_andamento',
    prioridade: 'alta',
    responsavel_id: 'u1',
    equipe_ids: ['u1', 'u3'],
    data_inicio: '2026-03-01',
    data_entrega_prevista: '2026-06-30',
    progresso: 35,
    tags: ['ecommerce', 'branding', 'design'],
    criado_em: '2026-03-01T09:00:00Z',
    atualizado_em: '2026-04-23T11:00:00Z',
  },
  {
    id: 'p6',
    cliente_id: 'c5',
    contrato_id: 'k5',
    nome: 'Performance Marketing Março — Kredix',
    descricao: 'Gestão e otimização das campanhas Google + Meta do mês de março.',
    tipo: 'retainer_mensal',
    status: 'concluido',
    prioridade: 'normal',
    responsavel_id: 'u2',
    equipe_ids: ['u2'],
    data_inicio: '2026-03-01',
    data_entrega_prevista: '2026-03-31',
    data_entrega_real: '2026-03-31',
    progresso: 100,
    tags: ['performance', 'google-ads', 'meta-ads'],
    criado_em: '2026-03-01T09:00:00Z',
    atualizado_em: '2026-03-31T18:00:00Z',
  },
]

export const mockTarefas: Tarefa[] = [
  // ── Projeto 1: Social Media Studio K ───────────────────────────────────────
  {
    id: 't1', projeto_id: 'p1', ordem: 1,
    nome: 'Planejamento editorial de abril',
    tipo: 'estrategia', status: 'concluido',
    responsavel_id: 'u3', prioridade: 'normal',
    data_prevista: '2026-04-03', data_conclusao: '2026-04-02',
    estimativa_horas: 2, horas_realizadas: 1.5,
    revisoes_usadas: 0, revisoes_max: 1,
    criado_em: '2026-04-01T09:00:00Z', atualizado_em: '2026-04-02T16:00:00Z',
  },
  {
    id: 't2', projeto_id: 'p1', ordem: 2,
    nome: 'Copywriting — posts do feed (12 posts)',
    descricao: 'Legendas para 12 publicações no feed do Instagram, tom inspiracional + técnico.',
    tipo: 'copy', status: 'concluido',
    responsavel_id: 'u3', prioridade: 'normal',
    data_prevista: '2026-04-08', data_conclusao: '2026-04-07',
    estimativa_horas: 4, horas_realizadas: 5,
    revisoes_usadas: 1, revisoes_max: 2,
    criado_em: '2026-04-01T09:00:00Z', atualizado_em: '2026-04-07T17:00:00Z',
  },
  {
    id: 't3', projeto_id: 'p1', ordem: 3,
    nome: 'Design — artes do feed (12 peças)',
    descricao: 'Criação das 12 artes do feed seguindo identidade visual do Studio K.',
    tipo: 'design', status: 'em_andamento',
    responsavel_id: 'u3', prioridade: 'normal',
    data_prevista: '2026-04-26',
    estimativa_horas: 8, horas_realizadas: 5,
    revisoes_usadas: 0, revisoes_max: 2,
    criado_em: '2026-04-08T09:00:00Z', atualizado_em: '2026-04-22T15:00:00Z',
  },
  {
    id: 't4', projeto_id: 'p1', ordem: 4,
    nome: 'Design + Copy — stories (16 stories)',
    descricao: '16 stories com mix de conteúdo educativo e promocional.',
    tipo: 'design', status: 'aguardando_cliente',
    responsavel_id: 'u3', prioridade: 'alta',
    data_prevista: '2026-04-19',
    estimativa_horas: 5, horas_realizadas: 5,
    revisoes_usadas: 2, revisoes_max: 2,
    feedback_cliente: 'Ajustar a cor do botão CTA no story 3. Fonte do título muito pequena no mobile.',
    criado_em: '2026-04-10T09:00:00Z', atualizado_em: '2026-04-19T10:00:00Z',
  },
  {
    id: 't5', projeto_id: 'p1', ordem: 5,
    nome: 'Agendamento e publicação',
    tipo: 'publicacao', status: 'backlog',
    responsavel_id: 'u3', prioridade: 'normal',
    data_prevista: '2026-04-29',
    estimativa_horas: 1, horas_realizadas: 0,
    revisoes_usadas: 0, revisoes_max: 0,
    dependencia_ids: ['t3', 't4'],
    criado_em: '2026-04-01T09:00:00Z', atualizado_em: '2026-04-01T09:00:00Z',
  },

  // ── Projeto 2: Campanha Indústria 4.0 ──────────────────────────────────────
  {
    id: 't6', projeto_id: 'p2', ordem: 1,
    nome: 'Estratégia e planejamento da campanha',
    tipo: 'estrategia', status: 'concluido',
    responsavel_id: 'u1', prioridade: 'alta',
    data_prevista: '2026-04-03', data_conclusao: '2026-04-02',
    estimativa_horas: 3, horas_realizadas: 3,
    revisoes_usadas: 0, revisoes_max: 1,
    criado_em: '2026-04-01T09:00:00Z', atualizado_em: '2026-04-02T14:00:00Z',
  },
  {
    id: 't7', projeto_id: 'p2', ordem: 2,
    nome: 'Configuração Google Ads (3 campanhas)',
    tipo: 'configuracao', status: 'concluido',
    responsavel_id: 'u1', prioridade: 'alta',
    data_prevista: '2026-04-07', data_conclusao: '2026-04-06',
    estimativa_horas: 4, horas_realizadas: 5,
    revisoes_usadas: 0, revisoes_max: 0,
    criado_em: '2026-04-03T09:00:00Z', atualizado_em: '2026-04-06T16:00:00Z',
  },
  {
    id: 't8', projeto_id: 'p2', ordem: 3,
    nome: 'Criativos para Meta Ads — v1 aprovados',
    descricao: '6 criativos (3 formatos) aprovados pelo cliente na semana 1.',
    tipo: 'design', status: 'concluido',
    responsavel_id: 'u3', prioridade: 'alta',
    data_prevista: '2026-04-10', data_conclusao: '2026-04-09',
    estimativa_horas: 6, horas_realizadas: 7,
    revisoes_usadas: 1, revisoes_max: 2,
    criado_em: '2026-04-03T09:00:00Z', atualizado_em: '2026-04-09T15:00:00Z',
  },
  {
    id: 't9', projeto_id: 'p2', ordem: 4,
    nome: 'Otimização semanal — semana 3',
    descricao: 'Análise de performance, ajuste de lances, pausar criativos fracos.',
    tipo: 'configuracao', status: 'em_andamento',
    responsavel_id: 'u1', prioridade: 'alta',
    data_prevista: '2026-04-25',
    estimativa_horas: 2, horas_realizadas: 1,
    revisoes_usadas: 0, revisoes_max: 0,
    criado_em: '2026-04-21T09:00:00Z', atualizado_em: '2026-04-23T10:00:00Z',
  },
  {
    id: 't10', projeto_id: 'p2', ordem: 5,
    nome: 'Relatório parcial de performance',
    descricao: 'Relatório de meio de mês com métricas de CPL, impressões e conversões.',
    tipo: 'relatorio', status: 'revisao_interna',
    responsavel_id: 'u1', revisores_ids: ['u2'],
    prioridade: 'normal',
    data_prevista: '2026-04-25',
    estimativa_horas: 2, horas_realizadas: 2,
    revisoes_usadas: 0, revisoes_max: 1,
    criado_em: '2026-04-22T09:00:00Z', atualizado_em: '2026-04-24T09:00:00Z',
  },
  {
    id: 't11', projeto_id: 'p2', ordem: 6,
    nome: 'Relatório final + apresentação de resultados',
    tipo: 'relatorio', status: 'backlog',
    responsavel_id: 'u1', prioridade: 'normal',
    data_prevista: '2026-04-30',
    estimativa_horas: 3, horas_realizadas: 0,
    revisoes_usadas: 0, revisoes_max: 1,
    dependencia_ids: ['t9'],
    criado_em: '2026-04-01T09:00:00Z', atualizado_em: '2026-04-01T09:00:00Z',
  },

  // ── Projeto 3: Blog Q2 ──────────────────────────────────────────────────────
  {
    id: 't12', projeto_id: 'p3', ordem: 1,
    nome: 'Pesquisa de pautas e palavras-chave',
    descricao: 'Identificar 12 temas com potencial de ranqueamento no segmento industrial.',
    tipo: 'estrategia', status: 'em_andamento',
    responsavel_id: 'u1', prioridade: 'normal',
    data_prevista: '2026-04-25',
    estimativa_horas: 4, horas_realizadas: 2,
    revisoes_usadas: 0, revisoes_max: 1,
    criado_em: '2026-04-15T09:00:00Z', atualizado_em: '2026-04-20T11:00:00Z',
  },
  {
    id: 't13', projeto_id: 'p3', ordem: 2,
    nome: 'Produção Artigo 1 — Automação Industrial',
    tipo: 'copy', status: 'backlog',
    responsavel_id: 'u1', prioridade: 'normal',
    data_prevista: '2026-05-05',
    estimativa_horas: 3, horas_realizadas: 0,
    revisoes_usadas: 0, revisoes_max: 2,
    dependencia_ids: ['t12'],
    criado_em: '2026-04-15T09:00:00Z', atualizado_em: '2026-04-15T09:00:00Z',
  },

  // ── Projeto 4: Clínica NovaSaúde — URGENTE / EM RISCO ──────────────────────
  {
    id: 't14', projeto_id: 'p4', ordem: 1,
    nome: 'Briefing da campanha de consultas',
    tipo: 'briefing', status: 'concluido',
    responsavel_id: 'u2', prioridade: 'urgente',
    data_prevista: '2026-04-07', data_conclusao: '2026-04-06',
    estimativa_horas: 1, horas_realizadas: 1,
    revisoes_usadas: 0, revisoes_max: 0,
    criado_em: '2026-04-05T09:00:00Z', atualizado_em: '2026-04-06T14:00:00Z',
  },
  {
    id: 't15', projeto_id: 'p4', ordem: 2,
    nome: 'Criativos v1 — foco em agendamento',
    descricao: '8 peças focadas em conversão para agendamento de consultas.',
    tipo: 'design', status: 'concluido',
    responsavel_id: 'u3', prioridade: 'urgente',
    data_prevista: '2026-04-12', data_conclusao: '2026-04-11',
    estimativa_horas: 6, horas_realizadas: 7,
    revisoes_usadas: 1, revisoes_max: 2,
    criado_em: '2026-04-06T09:00:00Z', atualizado_em: '2026-04-11T17:00:00Z',
  },
  {
    id: 't16', projeto_id: 'p4', ordem: 3,
    nome: 'Criativos v2 — reposicionamento "bem-estar"',
    descricao: 'Refazer 8 criativos com foco em bem-estar preventivo (não doenças), conforme pedido da Dra. Helena.',
    tipo: 'design', status: 'bloqueado',
    responsavel_id: 'u3', prioridade: 'urgente',
    data_prevista: '2026-04-20',
    feedback_cliente: 'Refazer com foco em "bem-estar" e prevenção, não em doenças. Remover ícones de medicamentos.',
    estimativa_horas: 6, horas_realizadas: 0,
    revisoes_usadas: 2, revisoes_max: 2,
    dependencia_ids: ['t15'],
    criado_em: '2026-04-12T09:00:00Z', atualizado_em: '2026-04-19T14:00:00Z',
  },
  {
    id: 't17', projeto_id: 'p4', ordem: 4,
    nome: 'Configuração e veiculação das campanhas',
    tipo: 'configuracao', status: 'backlog',
    responsavel_id: 'u2', prioridade: 'urgente',
    data_prevista: '2026-04-25',
    estimativa_horas: 2, horas_realizadas: 0,
    revisoes_usadas: 0, revisoes_max: 0,
    dependencia_ids: ['t16'],
    criado_em: '2026-04-05T09:00:00Z', atualizado_em: '2026-04-05T09:00:00Z',
  },

  // ── Projeto 5: E-Bike Shop ──────────────────────────────────────────────────
  {
    id: 't18', projeto_id: 'p5', ordem: 1,
    nome: 'Briefing de identidade visual',
    tipo: 'briefing', status: 'concluido',
    responsavel_id: 'u1', prioridade: 'alta',
    data_prevista: '2026-03-10', data_conclusao: '2026-03-09',
    estimativa_horas: 2, horas_realizadas: 2,
    revisoes_usadas: 0, revisoes_max: 0,
    criado_em: '2026-03-01T09:00:00Z', atualizado_em: '2026-03-09T15:00:00Z',
  },
  {
    id: 't19', projeto_id: 'p5', ordem: 2,
    nome: 'Identidade Visual — logo, paleta, tipografia',
    descricao: 'Entrega completa: logo principal + 3 variações, paleta de cores, guia tipográfico.',
    tipo: 'design', status: 'aguardando_cliente',
    responsavel_id: 'u3', prioridade: 'alta',
    data_prevista: '2026-03-31',
    feedback_cliente: 'Logo aprovado! Quer testar a paleta com verde musgo escuro (#2D5016) ao invés do verde claro.',
    estimativa_horas: 12, horas_realizadas: 12,
    revisoes_usadas: 1, revisoes_max: 3,
    criado_em: '2026-03-10T09:00:00Z', atualizado_em: '2026-03-28T14:00:00Z',
  },
  {
    id: 't20', projeto_id: 'p5', ordem: 3,
    nome: 'Layout home page',
    tipo: 'design', status: 'backlog',
    responsavel_id: 'u3', prioridade: 'alta',
    data_prevista: '2026-05-15',
    estimativa_horas: 8, horas_realizadas: 0,
    revisoes_usadas: 0, revisoes_max: 2,
    dependencia_ids: ['t19'],
    criado_em: '2026-03-01T09:00:00Z', atualizado_em: '2026-03-01T09:00:00Z',
  },
  {
    id: 't21', projeto_id: 'p5', ordem: 4,
    nome: 'Layout páginas de produto',
    tipo: 'design', status: 'backlog',
    responsavel_id: 'u3', prioridade: 'alta',
    data_prevista: '2026-05-30',
    estimativa_horas: 10, horas_realizadas: 0,
    revisoes_usadas: 0, revisoes_max: 2,
    dependencia_ids: ['t20'],
    criado_em: '2026-03-01T09:00:00Z', atualizado_em: '2026-03-01T09:00:00Z',
  },
  {
    id: 't22', projeto_id: 'p5', ordem: 5,
    nome: 'Configuração e launch da loja',
    tipo: 'configuracao', status: 'backlog',
    responsavel_id: 'u1', prioridade: 'alta',
    data_prevista: '2026-06-20',
    estimativa_horas: 8, horas_realizadas: 0,
    revisoes_usadas: 0, revisoes_max: 1,
    dependencia_ids: ['t21'],
    criado_em: '2026-03-01T09:00:00Z', atualizado_em: '2026-03-01T09:00:00Z',
  },

  // ── Projeto 6: Kredix Março — CONCLUÍDO ─────────────────────────────────────
  {
    id: 't23', projeto_id: 'p6', ordem: 1,
    nome: 'Otimização campanhas março',
    tipo: 'configuracao', status: 'concluido',
    responsavel_id: 'u2', prioridade: 'normal',
    data_prevista: '2026-03-28', data_conclusao: '2026-03-27',
    estimativa_horas: 8, horas_realizadas: 9,
    revisoes_usadas: 0, revisoes_max: 0,
    criado_em: '2026-03-01T09:00:00Z', atualizado_em: '2026-03-27T17:00:00Z',
  },
  {
    id: 't24', projeto_id: 'p6', ordem: 2,
    nome: 'Relatório final de março',
    descricao: 'CPL: R$42 (meta R$60). Leads: 310 (meta 250). ROI: 4,2x.',
    tipo: 'relatorio', status: 'concluido',
    responsavel_id: 'u2', prioridade: 'normal',
    data_prevista: '2026-03-31', data_conclusao: '2026-03-31',
    estimativa_horas: 2, horas_realizadas: 2,
    revisoes_usadas: 0, revisoes_max: 1,
    criado_em: '2026-03-28T09:00:00Z', atualizado_em: '2026-03-31T18:00:00Z',
  },
]

export const mockComentarios: Comentario[] = [
  {
    id: 'cm1', tarefa_id: 't4',
    usuario_nome: 'Kleber Nunes (Cliente)',
    conteudo: 'Gostei da linha criativa! Só ajustar a cor do botão CTA para o verde da marca (#4CAF50) e aumentar a fonte do título em mobile.',
    tipo: 'feedback_cliente',
    criado_em: '2026-04-19T10:00:00Z',
  },
  {
    id: 'cm2', tarefa_id: 't10',
    usuario_nome: 'Lucas Andrade',
    conteudo: 'Relatório finalizado. Enviando para Ana revisar antes de mandar ao Marcos.',
    tipo: 'comentario',
    criado_em: '2026-04-24T09:00:00Z',
  },
  {
    id: 'cm3', tarefa_id: 't16',
    usuario_nome: 'Dra. Helena (Cliente)',
    conteudo: 'A linha visual estava muito focada em doença. Precisamos mudar o conceito para bem-estar preventivo. Referências: Mayo Clinic, Einstein.',
    tipo: 'feedback_cliente',
    criado_em: '2026-04-19T14:00:00Z',
  },
  {
    id: 'cm4', tarefa_id: 't19',
    usuario_nome: 'Bruno Almeida (Cliente)',
    conteudo: 'Adorei o logo! Vamos testar a paleta com o verde musgo mais escuro. Podem trazer mais 2 opções de variação?',
    tipo: 'feedback_cliente',
    criado_em: '2026-03-28T14:00:00Z',
  },
]
