import { Cliente, ContatoCliente, Contrato, EntregaHistorico } from './types'

export const mockClientes: Cliente[] = [
  {
    id: 'c1',
    lead_id: 'l7',
    nome_empresa: 'Studio K Arquitetura',
    cnpj: '44.321.987/0001-55',
    segmento: 'servicos',
    porte: 'micro',
    site: 'studiok.com.br',
    cidade: 'São Paulo',
    estado: 'SP',
    tipo: 'retainer',
    status: 'ativo',
    responsavel_id: 'u3',
    data_inicio: '2026-01-05',
    nps: 9,
    observacoes: 'Cliente satisfeito. Interesse em ampliar para produção de vídeo no Q3.',
    criado_em: '2026-01-05T10:00:00Z',
    atualizado_em: '2026-04-01T09:00:00Z',
  },
  {
    id: 'c2',
    nome_empresa: 'Grupo Industrial Santos',
    cnpj: '11.222.333/0001-44',
    segmento: 'industria',
    porte: 'grande',
    site: 'grupoindustrialsantos.com.br',
    cidade: 'Santo André',
    estado: 'SP',
    tipo: 'retainer',
    status: 'ativo',
    responsavel_id: 'u1',
    data_inicio: '2025-08-01',
    nps: 8,
    observacoes: 'Maior conta ativa. Renovação anual em agosto/2026. Alta prioridade.',
    criado_em: '2025-08-01T09:00:00Z',
    atualizado_em: '2026-04-01T09:00:00Z',
  },
  {
    id: 'c3',
    nome_empresa: 'Clínica NovaSaúde',
    cnpj: '77.888.999/0001-11',
    segmento: 'saude',
    porte: 'media',
    site: 'clinicanovasaude.com.br',
    cidade: 'Campinas',
    estado: 'SP',
    tipo: 'retainer',
    status: 'em_risco',
    motivo_risco: 'Três meses seguidos de pedidos de desconto. Diretora questionou ROI das campanhas.',
    responsavel_id: 'u2',
    data_inicio: '2025-11-01',
    nps: 6,
    criado_em: '2025-11-01T09:00:00Z',
    atualizado_em: '2026-04-20T14:00:00Z',
  },
  {
    id: 'c4',
    nome_empresa: 'E-Bike Shop',
    cnpj: '33.444.555/0001-22',
    segmento: 'ecommerce',
    porte: 'pequena',
    site: 'ebikeshop.com.br',
    cidade: 'Florianópolis',
    estado: 'SC',
    tipo: 'projeto',
    status: 'ativo',
    responsavel_id: 'u1',
    data_inicio: '2026-03-01',
    data_fim: '2026-06-30',
    criado_em: '2026-03-01T09:00:00Z',
    atualizado_em: '2026-04-10T11:00:00Z',
  },
  {
    id: 'c5',
    nome_empresa: 'Fintech Kredix',
    cnpj: '99.000.111/0001-33',
    segmento: 'saas',
    porte: 'media',
    site: 'kredix.com.br',
    cidade: 'São Paulo',
    estado: 'SP',
    tipo: 'performance',
    status: 'ativo',
    responsavel_id: 'u2',
    data_inicio: '2026-02-01',
    nps: 10,
    observacoes: 'Performance excepcional. CPL caiu 38% em 2 meses. Querem expandir para novos mercados.',
    criado_em: '2026-02-01T09:00:00Z',
    atualizado_em: '2026-04-22T10:00:00Z',
  },
  {
    id: 'c6',
    nome_empresa: 'Moda Verde Sustentável',
    cnpj: '55.666.777/0001-88',
    segmento: 'varejo',
    porte: 'pequena',
    cidade: 'Curitiba',
    estado: 'PR',
    tipo: 'projeto',
    status: 'encerrado',
    motivo_encerramento: 'Projeto de branding concluído com sucesso. Cliente sem budget para continuidade.',
    responsavel_id: 'u3',
    data_inicio: '2025-09-01',
    data_fim: '2026-01-31',
    nps: 8,
    criado_em: '2025-09-01T09:00:00Z',
    atualizado_em: '2026-02-01T09:00:00Z',
  },
]

export const mockContatos: ContatoCliente[] = [
  { id: 'ct1', cliente_id: 'c1', nome: 'Kleber Nunes', cargo: 'ceo_socio', email: 'kleber@studiok.com.br', whatsapp: '11976543210', principal: true },
  { id: 'ct2', cliente_id: 'c2', nome: 'Marcos Santos', cargo: 'diretor', email: 'marcos@grupoindustrialsantos.com.br', whatsapp: '11934567890', principal: true },
  { id: 'ct3', cliente_id: 'c2', nome: 'Carla Pimenta', cargo: 'gerente', email: 'carla@grupoindustrialsantos.com.br', whatsapp: '11923456789', principal: false },
  { id: 'ct4', cliente_id: 'c3', nome: 'Dra. Helena Meireles', cargo: 'ceo_socio', email: 'helena@clinicanovasaude.com.br', whatsapp: '19987654321', principal: true },
  { id: 'ct5', cliente_id: 'c4', nome: 'Bruno Almeida', cargo: 'ceo_socio', email: 'bruno@ebikeshop.com.br', whatsapp: '48991234567', principal: true },
  { id: 'ct6', cliente_id: 'c5', nome: 'Tatiana Voss', cargo: 'diretor', email: 'tatiana@kredix.com.br', whatsapp: '11997654321', principal: true },
  { id: 'ct7', cliente_id: 'c5', nome: 'Paulo Henrique', cargo: 'gerente', email: 'paulo@kredix.com.br', whatsapp: '11988765432', principal: false },
  { id: 'ct8', cliente_id: 'c6', nome: 'Lara Matos', cargo: 'ceo_socio', email: 'lara@modaverde.com.br', whatsapp: '41991234567', principal: true },
]

export const mockContratos: Contrato[] = [
  {
    id: 'k1',
    cliente_id: 'c1',
    descricao: 'Social Media + Tráfego Pago (Meta)',
    servico_ids: ['s4', 's2'],
    tipo: 'retainer',
    valor_mensal: 4800,
    data_inicio: '2026-01-05',
    revisoes_incluidas: 2,
    status: 'ativo',
    criado_em: '2026-01-05T10:00:00Z',
  },
  {
    id: 'k2',
    cliente_id: 'c2',
    descricao: 'Inbound Marketing Completo',
    servico_ids: ['s1', 's3', 's5', 's8'],
    tipo: 'retainer',
    valor_mensal: 12000,
    data_inicio: '2025-08-01',
    data_fim: '2026-07-31',
    duracao_meses: 12,
    revisoes_incluidas: 3,
    status: 'ativo',
    observacoes: 'Contrato anual. Renovação prevista para agosto/2026 com reajuste de 10%.',
    criado_em: '2025-08-01T09:00:00Z',
  },
  {
    id: 'k3',
    cliente_id: 'c3',
    descricao: 'Tráfego Pago + Conteúdo',
    servico_ids: ['s1', 's3'],
    tipo: 'retainer',
    valor_mensal: 7200,
    data_inicio: '2025-11-01',
    revisoes_incluidas: 2,
    status: 'ativo',
    criado_em: '2025-11-01T09:00:00Z',
  },
  {
    id: 'k4',
    cliente_id: 'c4',
    descricao: 'Redesign + Lançamento E-commerce',
    servico_ids: ['s7', 's11', 's2'],
    tipo: 'projeto',
    valor_total: 18000,
    data_inicio: '2026-03-01',
    data_fim: '2026-06-30',
    duracao_meses: 4,
    revisoes_incluidas: 3,
    status: 'ativo',
    criado_em: '2026-03-01T09:00:00Z',
  },
  {
    id: 'k5',
    cliente_id: 'c5',
    descricao: 'Performance Marketing (Google + Meta)',
    servico_ids: ['s1', 's2'],
    tipo: 'performance',
    valor_base: 8000,
    valor_mensal: 14200,
    data_inicio: '2026-02-01',
    revisoes_incluidas: 1,
    status: 'ativo',
    observacoes: 'Base de R$ 8.000 + variável sobre leads gerados (R$ 18/lead acima da meta).',
    criado_em: '2026-02-01T09:00:00Z',
  },
  {
    id: 'k6',
    cliente_id: 'c6',
    descricao: 'Branding + Identidade Visual Completa',
    servico_ids: ['s7', 's11'],
    tipo: 'projeto',
    valor_total: 12000,
    data_inicio: '2025-09-01',
    data_fim: '2026-01-31',
    duracao_meses: 5,
    revisoes_incluidas: 2,
    status: 'encerrado',
    criado_em: '2025-09-01T09:00:00Z',
  },
]

export const mockEntregas: EntregaHistorico[] = [
  // Studio K
  {
    id: 'e1', cliente_id: 'c1', contrato_id: 'k1',
    titulo: 'Relatório de Performance — Março/2026',
    descricao: 'Relatório mensal com resultados de tráfego pago e social media.',
    tipo: 'relatorio_mensal', competencia: '2026-03',
    data_entrega: '2026-04-02T10:00:00Z',
    status: 'aprovado', revisoes_usadas: 0, revisoes_max: 2,
    responsavel_nome: 'Rafael Mendes',
  },
  {
    id: 'e2', cliente_id: 'c1', contrato_id: 'k1',
    titulo: 'Pack de Criativos — Abril/2026',
    descricao: '6 artes para feed + 4 stories com tema "Projetos de Interiores".',
    tipo: 'criativo', competencia: '2026-04',
    data_entrega: '2026-04-10T14:00:00Z',
    status: 'em_revisao', feedback: 'Fontes OK. Ajustar cor do botão no story 2.',
    revisoes_usadas: 1, revisoes_max: 2,
    responsavel_nome: 'Rafael Mendes',
  },
  // Grupo Industrial Santos
  {
    id: 'e3', cliente_id: 'c2', contrato_id: 'k2',
    titulo: 'Planejamento de Conteúdo — Q2/2026',
    descricao: 'Calendário editorial completo de abril a junho, 20 pautas de blog + LinkedIn.',
    tipo: 'planejamento', competencia: '2026-04',
    data_entrega: '2026-04-01T09:00:00Z',
    status: 'aprovado', revisoes_usadas: 0, revisoes_max: 3,
    responsavel_nome: 'Lucas Andrade',
  },
  {
    id: 'e4', cliente_id: 'c2', contrato_id: 'k2',
    titulo: 'Relatório de Performance — Março/2026',
    tipo: 'relatorio_mensal', competencia: '2026-03',
    data_entrega: '2026-04-03T10:00:00Z',
    status: 'aprovado', revisoes_usadas: 0, revisoes_max: 3,
    responsavel_nome: 'Lucas Andrade',
  },
  {
    id: 'e5', cliente_id: 'c2', contrato_id: 'k2',
    titulo: 'Campanha "Indústria 4.0" — Abril',
    descricao: 'Campanha de Google Ads para captação de leads B2B segmento industrial.',
    tipo: 'campanha', competencia: '2026-04',
    data_entrega: '2026-04-08T11:00:00Z',
    status: 'aprovado', revisoes_usadas: 1, revisoes_max: 3,
    responsavel_nome: 'Lucas Andrade',
  },
  // Clínica NovaSaúde
  {
    id: 'e6', cliente_id: 'c3', contrato_id: 'k3',
    titulo: 'Relatório de Performance — Março/2026',
    tipo: 'relatorio_mensal', competencia: '2026-03',
    data_entrega: '2026-04-02T10:00:00Z',
    status: 'entregue', feedback: 'Aguardando retorno da diretora.',
    revisoes_usadas: 0, revisoes_max: 2,
    responsavel_nome: 'Ana Costa',
  },
  {
    id: 'e7', cliente_id: 'c3', contrato_id: 'k3',
    titulo: 'Criativos Campanha Consultas — Abril',
    descricao: '8 artes para Meta Ads focadas em agendamentos de consulta.',
    tipo: 'criativo', competencia: '2026-04',
    data_entrega: '2026-04-05T14:00:00Z',
    status: 'rejeitado', feedback: 'Diretora solicitou refazer com foco em "bem-estar" e não "doença".',
    revisoes_usadas: 2, revisoes_max: 2,
    responsavel_nome: 'Ana Costa',
  },
  // E-Bike Shop
  {
    id: 'e8', cliente_id: 'c4', contrato_id: 'k4',
    titulo: 'Briefing de Identidade Visual',
    tipo: 'apresentacao', competencia: '2026-03',
    data_entrega: '2026-03-10T10:00:00Z',
    status: 'aprovado', revisoes_usadas: 0, revisoes_max: 3,
    responsavel_nome: 'Lucas Andrade',
  },
  {
    id: 'e9', cliente_id: 'c4', contrato_id: 'k4',
    titulo: 'Identidade Visual — v1',
    descricao: 'Logo principal, variações, paleta de cores, tipografia.',
    tipo: 'identidade_visual', competencia: '2026-03',
    data_entrega: '2026-03-25T15:00:00Z',
    status: 'em_revisao', feedback: 'Gostou do logo. Quer testar paleta em verde escuro.',
    revisoes_usadas: 1, revisoes_max: 3,
    responsavel_nome: 'Lucas Andrade',
  },
  // Fintech Kredix
  {
    id: 'e10', cliente_id: 'c5', contrato_id: 'k5',
    titulo: 'Relatório de Performance — Março/2026',
    descricao: 'CPL: R$42 (meta: R$60). Leads: 310 (meta: 250). ROI: 4,2x.',
    tipo: 'relatorio_mensal', competencia: '2026-03',
    data_entrega: '2026-04-02T09:00:00Z',
    status: 'aprovado', revisoes_usadas: 0, revisoes_max: 1,
    responsavel_nome: 'Ana Costa',
  },
  {
    id: 'e11', cliente_id: 'c5', contrato_id: 'k5',
    titulo: 'Campanha Captação — Abril/2026',
    descricao: 'Novas criativos para Google Search + Meta. 3 conjuntos de anúncios.',
    tipo: 'campanha', competencia: '2026-04',
    data_entrega: '2026-04-08T10:00:00Z',
    status: 'aprovado', revisoes_usadas: 0, revisoes_max: 1,
    responsavel_nome: 'Ana Costa',
  },
]
